# Valeurs base64 :
#   echo -n "defizz"   | base64  → ZGVmaXp6
#   echo -n "postgres" | base64  → cG9zdGdyZXM=
#   echo -n "pgpassword" | base64 → cGdwYXNzd29yZA==

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: defizz
type: Opaque
data:
  POSTGRES_DB:       ZGVmaXp6         # defizz
  POSTGRES_USER:     cG9zdGdyZXM=    # postgres
  POSTGRES_PASSWORD: cGdwYXNzd29yZA== # pgpassword
